// SPDX-License-Identifier: MPL-2.0
#pragma once

#include "anopki/crypto/backend.hpp"

#include <string>
#include <vector>

namespace anopki::crypto {

struct ProductProfileInfo
{
    std::string id;
    std::string edition;
    std::string selected_backend;
    bool fallback_enabled{false};
    std::vector<BackendCapability> required_capabilities;
};

// Defined by the selected product adapter. Each product artifact links exactly
// one implementation; adapters are never switched automatically at runtime.
[[nodiscard]] const Backend &default_backend();

// Build-time product profile metadata generated by CMake.
[[nodiscard]] const ProductProfileInfo &selected_product_profile() noexcept;

// Validate adapter identity, readiness, and profile-required capabilities.
// These functions throw BackendError with stable backend.* codes.
void validate_selected_backend();
void require_backend_capability(const Backend &backend, BackendCapability capability);
[[nodiscard]] const Backend &selected_backend();

// Error reporting must not rethrow when the selected dependency failed to
// initialize. This helper returns empty diagnostics on any adapter failure.
[[nodiscard]] ErrorDiagnostics drain_selected_backend_diagnostics() noexcept;

}  // namespace anopki::crypto
